//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_Client.ServiceReference1.Galamb))]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Galamb", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Galamb : WCF_Client.ServiceReference1.Record {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EletkorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FajtaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GazdaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte LabakSzamaField;
        
        private System.Nullable<bool> NemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Eletkor {
            get {
                return this.EletkorField;
            }
            set {
                if ((this.EletkorField.Equals(value) != true)) {
                    this.EletkorField = value;
                    this.RaisePropertyChanged("Eletkor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fajta {
            get {
                return this.FajtaField;
            }
            set {
                if ((object.ReferenceEquals(this.FajtaField, value) != true)) {
                    this.FajtaField = value;
                    this.RaisePropertyChanged("Fajta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gazda {
            get {
                return this.GazdaField;
            }
            set {
                if ((object.ReferenceEquals(this.GazdaField, value) != true)) {
                    this.GazdaField = value;
                    this.RaisePropertyChanged("Gazda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte LabakSzama {
            get {
                return this.LabakSzamaField;
            }
            set {
                if ((this.LabakSzamaField.Equals(value) != true)) {
                    this.LabakSzamaField = value;
                    this.RaisePropertyChanged("LabakSzama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> Nem {
            get {
                return this.NemField;
            }
            set {
                if ((this.NemField.Equals(value) != true)) {
                    this.NemField = value;
                    this.RaisePropertyChanged("Nem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambGet", ReplyAction="http://tempuri.org/IService1/EgyGalambGetResponse")]
        WCF_Client.ServiceReference1.Galamb EgyGalambGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambGet", ReplyAction="http://tempuri.org/IService1/EgyGalambGetResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambGetCS", ReplyAction="http://tempuri.org/IService1/EgyGalambGetCSResponse")]
        WCF_Client.ServiceReference1.Galamb EgyGalambGetCS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambGetCS", ReplyAction="http://tempuri.org/IService1/EgyGalambGetCSResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambGetCSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambPostCS", ReplyAction="http://tempuri.org/IService1/EgyGalambPostCSResponse")]
        WCF_Client.ServiceReference1.Galamb EgyGalambPostCS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambPostCS", ReplyAction="http://tempuri.org/IService1/EgyGalambPostCSResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambPostCSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambPost", ReplyAction="http://tempuri.org/IService1/EgyGalambPostResponse")]
        WCF_Client.ServiceReference1.Galamb EgyGalambPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyGalambPost", ReplyAction="http://tempuri.org/IService1/EgyGalambPostResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GalambLista", ReplyAction="http://tempuri.org/IService1/GalambListaResponse")]
        WCF_Client.ServiceReference1.Galamb[] GalambLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GalambLista", ReplyAction="http://tempuri.org/IService1/GalambListaResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb[]> GalambListaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Client.ServiceReference1.IService1>, WCF_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Client.ServiceReference1.Galamb EgyGalambGet() {
            return base.Channel.EgyGalambGet();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambGetAsync() {
            return base.Channel.EgyGalambGetAsync();
        }
        
        public WCF_Client.ServiceReference1.Galamb EgyGalambGetCS() {
            return base.Channel.EgyGalambGetCS();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambGetCSAsync() {
            return base.Channel.EgyGalambGetCSAsync();
        }
        
        public WCF_Client.ServiceReference1.Galamb EgyGalambPostCS() {
            return base.Channel.EgyGalambPostCS();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambPostCSAsync() {
            return base.Channel.EgyGalambPostCSAsync();
        }
        
        public WCF_Client.ServiceReference1.Galamb EgyGalambPost() {
            return base.Channel.EgyGalambPost();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb> EgyGalambPostAsync() {
            return base.Channel.EgyGalambPostAsync();
        }
        
        public WCF_Client.ServiceReference1.Galamb[] GalambLista() {
            return base.Channel.GalambLista();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Galamb[]> GalambListaAsync() {
            return base.Channel.GalambListaAsync();
        }
    }
}
